(function(){
  const LANG = {
    de: {
      'nav.how': 'Wie es funktioniert',
      'nav.eligibility': 'Wer hat Anspruch',
      'nav.calc': 'Rechner',
      'nav.cta': 'Kostenlos prüfen',
      'hero.eyebrow': 'Für pflegende Angehörige in der Schweiz',
      'hero.title': 'Du pflegst.<br><em>Wusstest du,</em><br>dass du dafür<br>bezahlt werden kannst?',
      'hero.lead': 'Über <strong>300\'000 Menschen</strong> in der Schweiz pflegen Angehörige zuhause – die meisten kostenlos und ohne Unterstützung. Dabei haben viele Anspruch auf eine offizielle Entlöhnung.',
      'hero.cta': 'Anspruch jetzt prüfen — kostenlos',
      'hero.ghost': 'Zum Rechner →',
      'stat1.label': 'Betroffene in der Schweiz',
      'stat2.label': 'CHF pro Monat verdienst möglich',
      'stat3.label': 'Pflegende bekommen nichts',
      'how.eyebrow': 'Wie es funktioniert',
      'how.title': '3 Schritte. <em>Kein Aufwand.</em>',
      'how.lead': 'Wir erledigen den Rest – du pflegst.',
      'how.step1.title': 'Anspruch online prüfen',
      'how.step1.desc': 'Fülle unser 2-Minuten-Formular aus. Wir prüfen, ob du Anspruch auf eine Entlöhnung hast.',
      'how.step1.highlight': '100% kostenlos',
      'how.step2.title': 'Persönliche Beratung erhalten',
      'how.step2.desc': 'Unser Team meldet sich innert 24 Stunden und erklärt dir genau, wie die Entlöhnung funktioniert.',
      'how.step2.highlight': 'Innert 24 Stunden',
      'how.step3.title': 'Angestellt werden & Lohn erhalten',
      'how.step3.desc': 'Wir vermitteln dich an eine geprüfte Spitex-Organisation in deiner Region. Du wirst offiziell angestellt und erhältst einen Monatslohn.',
      'how.step3.highlight': 'CHF 35–45 / Stunde',
      'elig.eyebrow': 'Voraussetzungen',
      'elig.title': 'Wer hat <em>Anspruch?</em>',
      'elig.subtitle': 'Fast jeder pflegende Angehörige. Hier sind die Kriterien:',
      'elig.c1.title': 'Du pflegst regelmässig',
      'elig.c1.desc': 'Mindestens ein paar Stunden pro Woche zuhause bei der pflegebedürftigen Person.',
      'elig.c2.title': 'Die Person ist pflegebedürftig',
      'elig.c2.desc': 'Alter, Krankheit oder Behinderung – eine anerkannte Pflegebedürftigkeit liegt vor.',
      'elig.c3.title': 'Du bist Angehörige/r',
      'elig.c3.desc': 'Familienmitglied, Partner/in oder Lebenspartner/in – eine persönliche Beziehung besteht.',
      'elig.c4.title': 'Du lebst in der Schweiz',
      'elig.c4.desc': 'Wohnsitz in der Schweiz ist Voraussetzung für den Spitex-Anschluss.',
      'elig.c5.title': 'Keine aktuelle Anstellung',
      'elig.c5.desc': 'Du pflegst bisher unentgeltlich – ohne offizielle Anstellung als Pflegeperson.',
      'elig.c6.title': 'Bereitschaft zur Anstellung',
      'elig.c6.desc': 'Du bist bereit, dich offiziell bei einer Spitex-Organisation anstellen zu lassen.',
      'calc.eyebrow': 'Dein stiller Verlust',
      'calc.title': 'Jede Stunde Pflege hat einen Preis. <em>Du bekommst ihn nur noch nicht.</em>',
      'calc.dur.label': 'Seit wann pflegst du bereits?',
      'calc.dur.min': '1 Monat',
      'calc.dur.max': '5+ Jahre',
      'calc.hrs.label': 'Stunden pro Woche',
      'calc.hrs.min': '1 Std.',
      'calc.hrs.max': '42 Std. (Vollzeit)',
      'calc.monthly.label': 'Dein monatlicher Lohn ab jetzt',
      'calc.monthly.default': 'Wähle Angaben links',
      'calc.hourly.label': 'Stundenlohn (Spitex)',
      'calc.hourly.val': 'ca. CHF 35–45 / Std.',
      'calc.yearly.label': 'Pro Jahr',
      'calc.missed.label': 'Was du bisher verpasst hast',
      'calc.cta': 'Jetzt keine Entlöhnung mehr verpassen',
      'cta.eyebrow': 'Kostenlose Prüfung',
      'cta.title': 'Prüfe deinen Anspruch in <em>2 Minuten.</em>',
      'cta.desc': '6 Fragen. Unverbindlich. Wir melden uns innert 24h mit einer klaren Einschätzung deines Anspruchs und dem passenden Spitex-Partner.',
      'quiz.step1.q': 'Pflegst du aktuell jemanden zuhause?',
      'quiz.step1.sub': 'Körperliche oder psychische Unterstützung zählt.',
      'quiz.step1.opt1': 'Ja, ein paar Stunden pro Woche<span>Ich helfe regelmässig, aber nicht täglich</span>',
      'quiz.step1.opt2': 'Ja, täglich / fast täglich<span>Pflege ist Teil meines Alltags</span>',
      'quiz.step1.opt3': 'Ja, rund um die Uhr<span>Vollzeitpflege zuhause</span>',
      'quiz.step1.opt4': 'Nein / bin unsicher<span>Ich bin mir nicht sicher ob ich pflege</span>',
      'quiz.step2.q': 'Wie viele Stunden pflegst du pro Woche?',
      'quiz.step2.sub': 'Alle Pflegeaktivitäten zusammengezählt.',
      'quiz.step2.unit': 'Std. / Woche',
      'quiz.step3.q': 'Wen pflegst du?',
      'quiz.step3.sub': 'Beziehung zur pflegebedürftigen Person.',
      'quiz.step3.opt1': '👴 Elternteil<span>Mutter oder Vater</span>',
      'quiz.step3.opt2': '💑 Partner / Ehepartner<span>Lebenspartner:in</span>',
      'quiz.step3.opt3': '👨‍👩‍👧 Geschwister / andere Verwandte<span>Schwester, Bruder, Grosseltern</span>',
      'quiz.step4.q': 'Welche Tätigkeiten übernimmst du?',
      'quiz.step4.sub': 'Mehrere Antworten möglich.',
      'quiz.step4.opt1': '🛁 Körperpflege<span>Waschen, anziehen, Mundhygiene</span>',
      'quiz.step4.opt2': '🚶 Mobilität & Transfer<span>Gehen begleiten, Lagern, Rollstuhl</span>',
      'quiz.step4.opt3': '🍽️ Ernährung<span>Essen eingeben, Trinken reichen</span>',
      'quiz.step4.opt4': '🌙 Nächtliche Betreuung<span>Aufstehen, Überwachung</span>',
      'quiz.step4.err': 'Bitte mindestens eine Tätigkeit auswählen.',
      'quiz.step5.q': 'In welchem Kanton wohnst du?',
      'quiz.step5.sub': 'Wir finden den passenden Spitex-Partner in deiner Region.',
      'quiz.step5.placeholder': 'Kanton auswählen…',
      'quiz.step5.err': 'Bitte einen Kanton auswählen.',
      'quiz.step6.q': 'Wie sollen wir uns melden?',
      'quiz.step6.sub': 'Kostenlos. Unverbindlich. Innert 24 Stunden.',
      'quiz.step6.vorname': 'Vorname',
      'quiz.step6.nachname': 'Nachname',
      'quiz.step6.phone': '+41 79 123 45 67',
      'quiz.step6.email': 'E-Mail-Adresse',
      'quiz.step6.consent': 'Mit dem Absenden dieses Formulars bestätige ich, dass ich die <a href="agb.html" target="_blank" style="color:var(--muted); text-decoration:underline;">Allgemeinen Geschäftsbedingungen</a> sowie die <a href="datenschutz.html" target="_blank" style="color:var(--muted); text-decoration:underline;">Datenschutzerklärung</a> von cuidesa.ch gelesen habe und damit einverstanden bin.',
      'quiz.step6.err.name': 'Bitte Vorname und Nachname eingeben.',
      'quiz.step6.err.phone': 'Bitte eine gültige Schweizer Nummer eingeben (z.B. +41 79 123 45 67).',
      'quiz.step6.err.email': 'Bitte eine gültige E-Mail-Adresse eingeben.',
      'quiz.back': '← Zurück',
      'quiz.next': 'Weiter →',
      'quiz.submit': 'Anspruch prüfen lassen →',
      'quiz.sending': 'Wird gesendet...',
      'quiz.done.title': 'Anfrage erhalten!',
      'quiz.done.sub': 'Wir melden uns <strong>innert 24 Stunden</strong> mit einer klaren Einschätzung deines Anspruchs und dem passenden Spitex-Partner in deiner Region.',
      'quiz.done.id': 'Deine Anfragen-ID:',
      'testi.eyebrow': 'Was Angehörige sagen',
      'testi.title': 'Echte Stimmen. <em>Echte Entlöhnung.</em>',
      'footer.desc': 'Wir helfen pflegenden Angehörigen in der Schweiz, die Entlöhnung zu erhalten, die ihnen zusteht.',
      'footer.nav.title': 'Navigation',
      'footer.nav.how': 'Wie es funktioniert',
      'footer.nav.elig': 'Wer hat Anspruch',
      'footer.nav.calc': 'Anspruch prüfen',
      'footer.contact.title': 'Kontakt',
      'footer.copy': '© 2025 Cuidesa. Alle Rechte vorbehalten.',
      'footer.tagline': 'Für pflegende Angehörige in der Schweiz',
      'footer.startseite': 'Startseite',
      'footer.datenschutz': 'Datenschutz',
      'footer.impressum': 'Impressum',
      'footer.agb': 'AGB',
      'agb.title': 'Allgemeine Geschäftsbedingungen (AGB)',
      'agb.meta': 'Cuidesa – Ermir Krasniqi, Romanshorn TG &nbsp;|&nbsp; Stand: März 2026',
      'agb.h1': '1. Geltungsbereich',
      'agb.p1': 'Diese AGB regeln die Nutzung der Plattform Cuidesa (www.cuidesa.ch) sowie die Geschäftsbeziehungen zwischen Cuidesa, vertreten durch Ermir Krasniqi, und Spitex-Organisationen oder anderen Partnern (nachfolgend „Kunden" genannt). Mit der Nutzung der Plattform oder dem Bezug von Dienstleistungen erklärt sich der Kunde mit diesen AGB einverstanden.',
      'agb.h2': '2. Leistungen',
      'agb.p2': 'Cuidesa ist eine Onlineplattform zur Lead-Generierung im Bereich Angehörigenpflege. Die Plattform vermittelt Kontaktanfragen von pflegenden Angehörigen an geprüfte Spitex-Organisationen in der Schweiz. Cuidesa stellt den Partnern die generierten Leads in Rechnung. Cuidesa ist kein Pflegedienstleister und erbringt keine Pflegeleistungen selbst. Cuidesa übernimmt keine Anstellung von Pflegepersonen und ist nicht Teil des Vertragsverhältnisses zwischen Angehörigen und Spitex-Organisation.',
      'agb.h3': '3. Vertragsabschluss',
      'agb.p3': 'Ein Vertrag zwischen Cuidesa und dem Kunden entsteht durch die Annahme eines Angebots oder den Erhalt und die Nutzung der vermittelten Leads. Der Kunde verpflichtet sich, die übermittelten Leads ausschliesslich für eigene geschäftliche Zwecke zu verwenden und nicht an Dritte weiterzugeben.',
      'agb.h4': '4. Preise und Zahlung',
      'agb.p4': 'Cuidesa stellt die Leistungen per Rechnung aus. Die Zahlung ist innert 14 Tagen ab Rechnungsdatum fällig, sofern nichts anderes vereinbart wurde. Alle Preise verstehen sich in Schweizer Franken (CHF), exkl. MwSt. (Einzelfirma ohne MwSt.-Pflicht unter CHF 100\'000 Umsatz).',
      'agb.h5': '5. Qualität der Leads',
      'agb.p5': 'Cuidesa prüft eingehende Anfragen auf Plausibilität, übernimmt jedoch keine Garantie für die Richtigkeit oder Vollständigkeit der Angaben der Interessenten. Ein Lead gilt als vermittelt sobald die Kontaktdaten übermittelt wurden — unabhängig davon ob eine Anstellung zustande kommt.',
      'agb.h6': '6. Haftung',
      'agb.p6': 'Cuidesa übernimmt keine Garantie dafür, dass eine Anfrage zu einer formellen Anstellung oder einem Vertragsabschluss führt. Jegliche Haftung für entgangenen Gewinn, Folgeschäden oder indirekte Schäden ist ausgeschlossen.',
      'agb.h7': '7. Datenschutz',
      'agb.p7': 'Cuidesa behandelt alle personenbezogenen Daten gemäss den geltenden Datenschutzbestimmungen (DSG/DSGVO). Details sind in der <a href="/datenschutz.html">Datenschutzerklärung</a> geregelt.',
      'agb.h8': '8. Änderungen',
      'agb.p8': 'Cuidesa behält sich das Recht vor, diese AGB jederzeit zu ändern. Massgeblich ist die zum Zeitpunkt der Nutzung gültige Fassung.',
      'agb.h9': '9. Gerichtsstand und anwendbares Recht',
      'agb.p9': 'Es gilt schweizerisches Recht. Gerichtsstand ist Romanshorn TG, soweit keine zwingenden gesetzlichen Bestimmungen vorgehen.',
      'agb.footer.note': 'Cuidesa – Ermir Krasniqi, Romanshorn TG',
      'ds.title': 'Datenschutzerklärung',
      'ds.h1': '1. Verantwortliche Stelle',
      'ds.p1': 'Cuidesa<br>Inhaber: Ermir Krasniqi<br>Romanshorn TG, Schweiz<br>E-Mail: <a href="mailto:info@cuidesa.ch">info@cuidesa.ch</a>',
      'ds.h2': '2. Erhobene Daten',
      'ds.p2': 'Beim Ausfüllen unseres Anspruchsformulars erheben wir folgende Daten: Name, Telefonnummer, Standort/Kanton/PLZ sowie Angaben zur Pflegesituation (Pflegebeziehung, Tätigkeiten, Wochenstunden). Zusätzlich werden technische Daten automatisch erfasst (z. B. IP-Adresse, Browsertyp, Besuchszeitpunkt).',
      'ds.h3': '3. Zweck der Datenerhebung',
      'ds.p3': 'Wir verwenden die Daten, um den Anspruch auf Entlöhnung als pflegende Angehörige zu prüfen, Interessentinnen und Interessenten mit passenden Spitex-Organisationen in ihrer Region zu verbinden sowie die Website und Marketingmassnahmen zu optimieren.',
      'ds.h4': '4. Weitergabe der Daten',
      'ds.p4': 'Personendaten werden ausschliesslich an Spitex-Organisationen weitergegeben, die mit Cuidesa zusammenarbeiten und für den jeweiligen Fall relevant sind. Eine Weitergabe an Dritte ausserhalb dieses Zwecks erfolgt nicht.',
      'ds.h5': '5. Tracking & Cookies',
      'ds.p5': 'Cuidesa kann Cookies und Tracking-Technologien (z. B. Google Analytics, Meta Pixel) einsetzen, um die Nutzung der Website zu analysieren und Werbung zu optimieren. Nutzer können Cookies in ihrem Browser deaktivieren – dies kann jedoch die Funktionalität der Website einschränken.',
      'ds.h6': '6. Datenspeicherung',
      'ds.p6': 'Personendaten werden nur so lange aufbewahrt, wie dies zur Erfüllung des jeweiligen Zwecks erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Formulardaten werden in einer gesicherten Google Sheets Umgebung gespeichert.',
      'ds.h7': '7. Rechte der betroffenen Personen',
      'ds.p7': 'Betroffene Personen haben das Recht auf Auskunft, Berichtigung, Löschung sowie Widerspruch gegen die Datenbearbeitung. Anfragen bitte an: <a href="mailto:info@cuidesa.ch">info@cuidesa.ch</a>',
      'ds.h8': '8. Datensicherheit',
      'ds.p8': 'Cuidesa trifft angemessene technische und organisatorische Massnahmen, um gespeicherte Daten vor unbefugtem Zugriff, Verlust oder Missbrauch zu schützen.',
      'ds.h9': '9. Anpassungen dieser Datenschutzerklärung',
      'ds.p9': 'Cuidesa kann diese Datenschutzerklärung jederzeit anpassen. Die aktuelle Version ist stets unter www.cuidesa.ch/datenschutz abrufbar.',
      'imp.title': 'Impressum',
      'imp.h1': 'Betreiber',
      'imp.h2': 'Kontakt'
    },
    sq: {
      'nav.how': 'Si funksionon',
      'nav.eligibility': 'Kush ka të drejtë',
      'nav.calc': 'Llogaritës',
      'nav.cta': 'Kontrollo falas',
      'hero.eyebrow': 'Për kujdestarët familjarë në Zvicër',
      'hero.title': 'Ti kujdesesh.<br><em>A e dije,</em><br>se mund të paguahesh<br>për këtë?',
      'hero.lead': 'Mbi <strong>300\'000 njerëz</strong> në Zvicër kujdesen për të afërmit në shtëpi – shumica falas dhe pa mbështetje. Shumë prej tyre kanë të drejtë për shpërblim zyrtar.',
      'hero.cta': 'Kontrollo të drejtën tani — falas',
      'hero.ghost': 'Tek llogaritësi →',
      'stat1.label': 'Të prekur në Zvicër',
      'stat2.label': 'CHF fitim i mundshëm në muaj',
      'stat3.label': 'Kujdestarë pa shpërblim',
      'how.eyebrow': 'Si funksionon',
      'how.title': '3 hapa. <em>Pa vështirësi.</em>',
      'how.lead': 'Ne bëjmë pjesën tjetër – ti kujdesesh.',
      'how.step1.title': 'Kontrollo të drejtën online',
      'how.step1.desc': 'Plotëso formularin tonë 2-minutësh. Ne kontrollojmë nëse ke të drejtë për shpërblim.',
      'how.step1.highlight': '100% falas',
      'how.step2.title': 'Merr këshillim personal',
      'how.step2.desc': 'Ekipi ynë kontakton brenda 24 orëve dhe shpjegon saktësisht si funksionon shpërblimi.',
      'how.step2.highlight': 'Brenda 24 orëve',
      'how.step3.title': 'Punësohu & merr pagën',
      'how.step3.desc': 'Ne të lidhim me një organizatë Spitex të verifikuar në rajonin tënd. Do të punësohesh zyrtarisht dhe do të marrësh pagë mujore.',
      'how.step3.highlight': 'CHF 35–45 / orë',
      'elig.eyebrow': 'Kushtet',
      'elig.title': 'Kush ka <em>të drejtë?</em>',
      'elig.subtitle': 'Pothuajse çdo kujdestar familjar. Këtu janë kriteret:',
      'elig.c1.title': 'Ti kujdesesh rregullisht',
      'elig.c1.desc': 'Të paktën disa orë në javë në shtëpi me personin që ka nevojë për kujdes.',
      'elig.c2.title': 'Personi ka nevojë për kujdes',
      'elig.c2.desc': 'Mosha, sëmundja ose paaftësia – ekziston një nevojë e njohur për kujdes.',
      'elig.c3.title': 'Ti je i/e afërt',
      'elig.c3.desc': 'Anëtar familjeje, partner/e ose bashkëshort/e – ekziston një marrëdhënie personale.',
      'elig.c4.title': 'Ti jeton në Zvicër',
      'elig.c4.desc': 'Vendbanimi në Zvicër është parakusht për lidhjen me Spitex.',
      'elig.c5.title': 'Pa punësim aktual',
      'elig.c5.desc': 'Deri tani ke kujdesur pa pagesë – pa punësim zyrtar si kujdestar.',
      'elig.c6.title': 'Gatishmëri për punësim',
      'elig.c6.desc': 'Je i/e gatshëm të punësohesh zyrtarisht pranë një organizate Spitex.',
      'calc.eyebrow': 'Humbja jote e heshtur',
      'calc.title': 'Çdo orë kujdesi ka një çmim. <em>Ti ende nuk e merr atë.</em>',
      'calc.dur.label': 'Që kur kujdesesh?',
      'calc.dur.min': '1 muaj',
      'calc.dur.max': '5+ vjet',
      'calc.hrs.label': 'Orë në javë',
      'calc.hrs.min': '1 orë',
      'calc.hrs.max': '42 orë (Kohë e plotë)',
      'calc.monthly.label': 'Paga jote mujore nga tani',
      'calc.monthly.default': 'Zgjidhni të dhënat majtas',
      'calc.hourly.label': 'Paga orare (Spitex)',
      'calc.hourly.val': 'afërsisht CHF 35–45 / orë',
      'calc.yearly.label': 'Në vit',
      'calc.missed.label': 'Çfarë ke humbur deri tani',
      'calc.cta': 'Mos humb më shpërblimin',
      'cta.eyebrow': 'Kontroll falas',
      'cta.title': 'Kontrollo të drejtën tënde në <em>2 minuta.</em>',
      'cta.desc': '6 pyetje. Pa detyrim. Kontaktojmë brenda 24h me një vlerësim të qartë të të drejtës tuaj dhe partnerin e duhur Spitex.',
      'quiz.step1.q': 'A po kujdesesh aktualisht për dikë në shtëpi?',
      'quiz.step1.sub': 'Mbështetja fizike ose psikologjike llogaritet.',
      'quiz.step1.opt1': 'Po, disa orë në javë<span>Ndihmoj rregullisht, por jo çdo ditë</span>',
      'quiz.step1.opt2': 'Po, çdo ditë / pothuajse çdo ditë<span>Kujdesi është pjesë e jetës sime të përditshme</span>',
      'quiz.step1.opt3': 'Po, gjatë gjithë kohës<span>Kujdes i plotë në shtëpi</span>',
      'quiz.step1.opt4': 'Jo / jam i pasigurt<span>Nuk jam i sigurt nëse kujdesem</span>',
      'quiz.step2.q': 'Sa orë në javë kujdesesh?',
      'quiz.step2.sub': 'Të gjitha aktivitetet e kujdesit bashkërisht.',
      'quiz.step2.unit': 'orë / javë',
      'quiz.step3.q': 'Për kë kujdesesh?',
      'quiz.step3.sub': 'Marrëdhënia me personin që ka nevojë për kujdes.',
      'quiz.step3.opt1': '👴 Prind<span>Nëna ose Babai</span>',
      'quiz.step3.opt2': '💑 Partner / Bashkëshort<span>Partner/e i/e jetës</span>',
      'quiz.step3.opt3': '👨‍👩‍👧 Vëlla / Motra / Të afërm<span>Motër, Vëlla, Gjyshërit</span>',
      'quiz.step4.q': 'Çfarë aktivitetesh merr përsipër?',
      'quiz.step4.sub': 'Më shumë se një përgjigje e mundshme.',
      'quiz.step4.opt1': '🛁 Kujdesi trupor<span>Larje, veshje, higjenë gojore</span>',
      'quiz.step4.opt2': '🚶 Lëvizja & Transferi<span>Shoqërim, pozicionim, karrocë</span>',
      'quiz.step4.opt3': '🍽️ Ushqyerja<span>Ushqyerje, dhënie pijesh</span>',
      'quiz.step4.opt4': '🌙 Kujdesi naktür<span>Zgjim, mbikëqyrje</span>',
      'quiz.step4.err': 'Ju lutemi zgjidhni të paktën një aktivitet.',
      'quiz.step5.q': 'Në cilin kanton jetoni?',
      'quiz.step5.sub': 'Ne gjejmë partnerin e duhur Spitex në rajonin tuaj.',
      'quiz.step5.placeholder': 'Zgjidhni kantonin…',
      'quiz.step5.err': 'Ju lutemi zgjidhni një kanton.',
      'quiz.step6.q': 'Si duhet të kontaktojmë?',
      'quiz.step6.sub': 'Falas. Pa detyrim. Brenda 24 orëve.',
      'quiz.step6.vorname': 'Emri',
      'quiz.step6.nachname': 'Mbiemri',
      'quiz.step6.phone': '+41 79 123 45 67',
      'quiz.step6.email': 'Adresa e email-it',
      'quiz.step6.consent': 'Duke dërguar këtë formular konfirmoj se kam lexuar <a href="agb.html" target="_blank" style="color:var(--muted); text-decoration:underline;">Kushtet e Përgjithshme</a> dhe <a href="datenschutz.html" target="_blank" style="color:var(--muted); text-decoration:underline;">Deklaratën e Privatësisë</a> të cuidesa.ch dhe jam dakord me to.',
      'quiz.step6.err.name': 'Ju lutemi vendosni emrin dhe mbiemrin.',
      'quiz.step6.err.phone': 'Ju lutemi vendosni një numër zviceran të vlefshëm (p.sh. +41 79 123 45 67).',
      'quiz.step6.err.email': 'Ju lutemi vendosni një adresë email të vlefshme.',
      'quiz.back': '← Kthehu',
      'quiz.next': 'Vazhdo →',
      'quiz.submit': 'Lejo kontrollin e të drejtave →',
      'quiz.sending': 'Duke dërguar...',
      'quiz.done.title': 'Kërkesa u pranua!',
      'quiz.done.sub': 'Do t\'ju kontaktojmë <strong>brenda 24 orëve</strong> me një vlerësim të qartë të të drejtës tuaj dhe partnerin e duhur Spitex në rajonin tuaj.',
      'quiz.done.id': 'ID-ja juaj e kërkesës:',
      'testi.eyebrow': 'Çfarë thonë të afërmit',
      'testi.title': 'Zëra të vërtetë. <em>Shpërblim i vërtetë.</em>',
      'footer.desc': 'Ne ndihmojmë kujdestarët familjarë në Zvicër të marrin shpërblimin që u takon.',
      'footer.nav.title': 'Navigimi',
      'footer.nav.how': 'Si funksionon',
      'footer.nav.elig': 'Kush ka të drejtë',
      'footer.nav.calc': 'Kontrollo të drejtën',
      'footer.contact.title': 'Kontakti',
      'footer.copy': '© 2025 Cuidesa. Të gjitha të drejtat e rezervuara.',
      'footer.tagline': 'Për kujdestarët familjarë në Zvicër',
      'footer.startseite': 'Faqja kryesore',
      'footer.datenschutz': 'Privatësia',
      'footer.impressum': 'Impressum',
      'footer.agb': 'Kushtet',
      'agb.title': 'Kushtet e Përgjithshme të Biznesit (AGB)',
      'agb.meta': 'Cuidesa – Ermir Krasniqi, Romanshorn TG &nbsp;|&nbsp; Versioni: Mars 2026',
      'agb.h1': '1. Fusha e zbatimit',
      'agb.p1': 'Këto kushte rregullojnë përdorimin e platformës Cuidesa (www.cuidesa.ch) dhe marrëdhëniet tregtare midis Cuidesa, të përfaqësuar nga Ermir Krasniqi, dhe organizatave Spitex ose partnerëve të tjerë (të quajtur \'klientë\'). Duke përdorur platformën ose shërbimet, klienti pranon këto kushte.',
      'agb.h2': '2. Shërbimet',
      'agb.p2': 'Cuidesa është një platformë online për gjenerimin e klientëve potencialë në fushën e kujdesit familjar. Platforma ndërmjetëson kërkesat e kontaktit nga kujdestarët familjarë tek organizatat Spitex të verifikuara në Zvicër. Cuidesa nuk është ofrues i kujdesit dhe nuk ofron shërbime kujdesi vetë.',
      'agb.h3': '3. Lidhja e kontratës',
      'agb.p3': 'Kontrata midis Cuidesa dhe klientit krijohet me pranimin e një oferte ose me marrjen dhe përdorimin e klientëve potencialë të ndërmjetësuar. Klienti angazhohet t\'i përdorë klientët e ndërmjetësuar vetëm për qëllime të veta tregtare.',
      'agb.h4': '4. Çmimet dhe pagesa',
      'agb.p4': 'Cuidesa lëshon fatura për shërbimet. Pagesa duhet bërë brenda 14 ditëve nga data e faturës, nëse nuk është rënë dakord ndryshe. Të gjitha çmimet janë në franga zvicerane (CHF), pa TVSH.',
      'agb.h5': '5. Cilësia e klientëve potencialë',
      'agb.p5': 'Cuidesa kontrollon kërkesat hyrëse për besueshmëri, por nuk garanton saktësinë ose plotësinë e të dhënave të dhëna. Një klient potencial konsiderohet i ndërmjetësuar sapo të dhënat e kontaktit janë transmetuar.',
      'agb.h6': '6. Përgjegjësia',
      'agb.p6': 'Cuidesa nuk garanton që një kërkesë do të çojë në punësim zyrtar. Çdo përgjegjësi për humbje fitimi, dëme pasuese ose dëme indirekte është e përjashtuar.',
      'agb.h7': '7. Mbrojtja e të dhënave',
      'agb.p7': 'Cuidesa trajton të gjitha të dhënat personale në përputhje me rregulloret aktuale të mbrojtjes së të dhënave (DSG/GDPR). Detajet janë rregulluar në <a href="/datenschutz.html">Deklaratën e Privatësisë</a>.',
      'agb.h8': '8. Ndryshimet',
      'agb.p8': 'Cuidesa rezervon të drejtën të ndryshojë këto kushte në çdo kohë. Versioni i vlefshëm është ai në kohën e përdorimit.',
      'agb.h9': '9. Juridiksioni dhe e drejta e zbatueshme',
      'agb.p9': 'Zbatohet e drejta zvicerane. Juridiksioni është Romanshorn TG, për aq sa nuk zbatohen dispozita ligjore urgjente.',
      'agb.footer.note': 'Cuidesa – Ermir Krasniqi, Romanshorn TG',
      'ds.title': 'Deklarata e Privatësisë',
      'ds.h1': '1. Pala përgjegjëse',
      'ds.p1': 'Cuidesa<br>Pronari: Ermir Krasniqi<br>Romanshorn TG, Zvicër<br>Email: <a href="mailto:info@cuidesa.ch">info@cuidesa.ch</a>',
      'ds.h2': '2. Të dhënat e mbledhura',
      'ds.p2': 'Kur plotësoni formularin tonë të kërkesës, mbledhim të dhënat e mëposhtme: emrin, numrin e telefonit, vendndodhjen/kantonin/ZIP si dhe informacion mbi situatën e kujdesit. Gjithashtu regjistrohen automatikisht të dhëna teknike (p.sh. adresa IP, lloji i shfletuesit, koha e vizitës).',
      'ds.h3': '3. Qëllimi i mbledhjes së të dhënave',
      'ds.p3': 'I përdorim të dhënat për të vlerësuar të drejtën për shpërblim si kujdestar familjar, për të lidhur personat e interesuar me organizatat Spitex dhe për të optimizuar faqen e internetit.',
      'ds.h4': '4. Ndarja e të dhënave',
      'ds.p4': 'Të dhënat personale u transmetohen vetëm organizatave Spitex që bashkëpunojnë me Cuidesa dhe janë relevante për rastin përkatës. Nuk bëhet asnjë transmetim tek palë të treta jashtë këtij qëllimi.',
      'ds.h5': '5. Gjurmimi & Cookies',
      'ds.p5': 'Cuidesa mund të përdorë cookies dhe teknologji gjurmimi (p.sh. Google Analytics, Meta Pixel) për të analizuar përdorimin e faqes. Përdoruesit mund të çaktivizojnë cookies në shfletuesin e tyre.',
      'ds.h6': '6. Ruajtja e të dhënave',
      'ds.p6': 'Të dhënat personale ruhen vetëm aq gjatë sa është e nevojshme për të përmbushur qëllimin përkatës. Të dhënat e formularëve ruhen në një mjedis të sigurt Google Sheets.',
      'ds.h7': '7. Të drejtat e personave të prekur',
      'ds.p7': 'Personat e prekur kanë të drejtë për informim, korrigjim, fshirje dhe kundërshtim ndaj përpunimit të të dhënave. Kërkesat dërgoni te: <a href="mailto:info@cuidesa.ch">info@cuidesa.ch</a>',
      'ds.h8': '8. Siguria e të dhënave',
      'ds.p8': 'Cuidesa merr masa të përshtatshme teknike dhe organizative për të mbrojtur të dhënat nga aksesi i paautorizuar, humbja ose keqpërdorimi.',
      'ds.h9': '9. Ndryshimet e kësaj deklarate',
      'ds.p9': 'Cuidesa mund ta përditësojë këtë deklaratë privatësie në çdo kohë. Versioni aktual është gjithmonë i disponueshëm në www.cuidesa.ch/datenschutz.',
      'imp.title': 'Impressum',
      'imp.h1': 'Operatori',
      'imp.h2': 'Kontakti'
    }
  };

  window.t = function(key) {
    const lang = localStorage.getItem('cuidesa_lang') || 'de';
    return (LANG[lang]||{})[key] || (LANG.de||{})[key] || key;
  };

  function applyTranslations(lang) {
    document.documentElement.lang = lang === 'sq' ? 'sq' : 'de';
    const T = LANG[lang] || LANG.de;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const k = el.getAttribute('data-i18n');
      if (T[k] !== undefined) el.innerHTML = T[k];
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const k = el.getAttribute('data-i18n-placeholder');
      if (T[k] !== undefined) el.placeholder = T[k];
    });
  }

  function setLanguage(lang) {
    localStorage.setItem('cuidesa_lang', lang);
    applyTranslations(lang);
    document.querySelectorAll('[data-lang-btn]').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.langBtn === lang);
    });
  }

  document.addEventListener('DOMContentLoaded', function() {
    const lang = localStorage.getItem('cuidesa_lang') || 'de';
    applyTranslations(lang);
    document.querySelectorAll('[data-lang-btn]').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.langBtn === lang);
      btn.addEventListener('click', function(){ setLanguage(this.dataset.langBtn); });
    });
  });
})();
